export default {
  af: {
    Code: "af",
    Name: "Afrikaans",
    NativeName: "Afrikaans",
    Flag: "af",
    rtl: false,
  },
  am: {
    Code: "am",
    Name: "Amharic",
    NativeName: "አማርኛ",
    Flag: "am",
    rtl: false,
  },
  ar: {
    Code: "ar",
    Name: "Arabic",
    NativeName: "اللغة العربية",
    Flag: "ag",
    rtl: true,
  },
  az: {
    Code: "az",
    Name: "Azerbaijani",
    NativeName: "Azərbaycan dili",
    Flag: "az",
    rtl: false,
  },
  be: {
    Code: "be",
    Name: "Belarusian",
    NativeName: "Беларуская мова",
    Flag: "be",
    rtl: false,
  },
  bg: {
    Code: "bg",
    Name: "Bulgarian",
    NativeName: "Български език",
    Flag: "bg",
    rtl: false,
  },
  bn: {
    Code: "bn",
    Name: "Bengali",
    NativeName: "বাংলা",
    Flag: "bn",
    rtl: false,
  },
  bs: {
    Code: "bs",
    Name: "Bosnian",
    NativeName: "Bosanski jezik",
    Flag: "bs",
    rtl: false,
  },
  ca: {
    Code: "ca",
    Name: "Catalan",
    NativeName: "Català",
    Flag: "ca",
    rtl: false,
  },
  cs: {
    Code: "cs",
    Name: "Czech",
    NativeName: "Čeština",
    Flag: "cs",
    rtl: false,
  },
  da: {
    Code: "da",
    Name: "Danish",
    NativeName: "Dansk",
    Flag: "da",
    rtl: false,
  },
  de: {
    Code: "de",
    Name: "German",
    NativeName: "Deutsch",
    Flag: "de",
    rtl: false,
  },
  el: {
    Code: "el",
    Name: "Greek",
    NativeName: "Ελληνικά",
    Flag: "el",
    rtl: false,
  },
  en: {
    Code: "en",
    Name: "English",
    NativeName: "English",
    Flag: "us",
    rtl: false,
  },
  es: {
    Code: "es",
    Name: "Spanish",
    NativeName: "Español",
    Flag: "es",
    rtl: false,
  },
  et: {
    Code: "et",
    Name: "Estonian",
    NativeName: "Eesti",
    Flag: "et",
    rtl: false,
  },
  fa: {
    Code: "fa",
    Name: "Persian",
    NativeName: "فارسی",
    Flag: "fa",
    rtl: false,
  },
  fi: {
    Code: "fi",
    Name: "Finnish",
    NativeName: "Suomi",
    Flag: "fi",
    rtl: false,
  },
  fr: {
    Code: "fr",
    Name: "French",
    NativeName: "Français",
    Flag: "fr",
    rtl: false,
  },
  ga: {
    Code: "ga",
    Name: "Irish",
    NativeName: "Gaeilge",
    Flag: "ga",
    rtl: false,
  },
  gl: {
    Code: "gl",
    Name: "Galician",
    NativeName: "Galego",
    Flag: "gl",
    rtl: false,
  },
  gu: {
    Code: "gu",
    Name: "Gujarati",
    NativeName: "ગુજરાતી",
    Flag: "gu",
    rtl: false,
  },
  he: {
    Code: "he",
    Name: "Hebrew",
    NativeName: "עברית",
    Flag: "he",
    rtl: false,
  },
  hi: {
    Code: "hi",
    Name: "Hindi",
    NativeName: "हिन्दी",
    Flag: "hi",
    rtl: false,
  },
  hr: {
    Code: "hr",
    Name: "Croatian",
    NativeName: "Hrvatski jezik",
    Flag: "hr",
    rtl: false,
  },
  hu: {
    Code: "hu",
    Name: "Hungarian",
    NativeName: "Magyar",
    Flag: "hu",
    rtl: false,
  },
  id: {
    Code: "id",
    Name: "Indonesian",
    NativeName: "Indonesian",
    Flag: "id",
    rtl: false,
  },
  is: {
    Code: "is",
    Name: "Icelandic",
    NativeName: "Íslenska",
    Flag: "is",
    rtl: false,
  },
  it: {
    Code: "it",
    Name: "Italian",
    NativeName: "Italiano",
    Flag: "it",
    rtl: false,
  },
  ja: {
    Code: "ja",
    Name: "Japanese",
    NativeName: "日本語",
    Flag: "ja",
    rtl: false,
  },
  jv: {
    Code: "jv",
    Name: "Javanese",
    NativeName: "Basa Jawa",
    Flag: "jv",
    rtl: false,
  },
  ka: {
    Code: "ka",
    Name: "Georgian",
    NativeName: "Ქართული",
    Flag: "ka",
    rtl: false,
  },
  kk: {
    Code: "kk",
    Name: "Kazakh",
    NativeName: "Қазақ тілі",
    Flag: "kk",
    rtl: false,
  },
  km: {
    Code: "km",
    Name: "Khmer",
    NativeName: "ខេមរភាសា",
    Flag: "km",
    rtl: false,
  },
  kn: {
    Code: "kn",
    Name: "Kannada",
    NativeName: "ಕನ್ನಡ",
    Flag: "kn",
    rtl: false,
  },
  ko: {
    Code: "ko",
    Name: "Korean",
    NativeName: "한국어",
    Flag: "ko",
    rtl: false,
  },
  ky: {
    Code: "ky",
    Name: "Kyrgyz",
    NativeName: "Кыргыз тили",
    Flag: "ky",
    rtl: false,
  },
  lo: {
    Code: "lo",
    Name: "Lao",
    NativeName: "ພາສາລາວ",
    Flag: "lo",
    rtl: false,
  },
  lt: {
    Code: "lt",
    Name: "Lithuanian",
    NativeName: "Lietuvių",
    Flag: "lt",
    rtl: false,
  },
  lv: {
    Code: "lv",
    Name: "Latvian",
    NativeName: "Latviešu",
    Flag: "lv",
    rtl: false,
  },
  mk: {
    Code: "mk",
    Name: "Macedonian",
    NativeName: "Македонски јазик",
    Flag: "mk",
    rtl: false,
  },
  ml: {
    Code: "ml",
    Name: "Malayalam",
    NativeName: "മലയാളം",
    Flag: "ml",
    rtl: false,
  },
  mn: {
    Code: "mn",
    Name: "Mongolian",
    NativeName: "Монгол хэл",
    Flag: "mn",
    rtl: false,
  },
  mr: {
    Code: "mr",
    Name: "Marathi",
    NativeName: "मराठी",
    Flag: "mr",
    rtl: false,
  },
  ms: {
    Code: "ms",
    Name: "Malay",
    NativeName: "Bahasa Melayu",
    Flag: "ms",
    rtl: false,
  },
  mt: {
    Code: "mt",
    Name: "Maltese",
    NativeName: "Malti",
    Flag: "mt",
    rtl: false,
  },
  my: {
    Code: "my",
    Name: "Burmese",
    NativeName: "မြန်မာစာ",
    Flag: "my",
    rtl: false,
  },
  ne: {
    Code: "ne",
    Name: "Nepali",
    NativeName: "नेपाली",
    Flag: "ne",
    rtl: false,
  },
  nl: {
    Code: "nl",
    Name: "Dutch",
    NativeName: "Nederlands",
    Flag: "nl",
    rtl: false,
  },
  no: {
    Code: "no",
    Name: "Norwegian",
    NativeName: "Norsk",
    Flag: "no",
    rtl: false,
  },
  pa: {
    Code: "pa",
    Name: "Punjabi",
    NativeName: "ਪੰਜਾਬੀ",
    Flag: "pa",
    rtl: false,
  },
  pl: {
    Code: "pl",
    Name: "Polish",
    NativeName: "Polski",
    Flag: "pl",
    rtl: false,
  },
  ps: {
    Code: "ps",
    Name: "Pashto",
    NativeName: "پښتو",
    Flag: "ps",
    rtl: false,
  },
  pt: {
    Code: "pt",
    Name: "Portuguese",
    NativeName: "Português",
    Flag: "pt",
    rtl: false,
  },
  ro: {
    Code: "ro",
    Name: "Romanian",
    NativeName: "Română",
    Flag: "ro",
    rtl: false,
  },
  ru: {
    Code: "ru",
    Name: "Russian",
    NativeName: "Русский",
    Flag: "ru",
    rtl: false,
  },
  si: {
    Code: "si",
    Name: "Sinhala",
    NativeName: "සිංහල",
    Flag: "si",
    rtl: false,
  },
  sk: {
    Code: "sk",
    Name: "Slovak",
    NativeName: "Slovenčina",
    Flag: "sk",
    rtl: false,
  },
  sl: {
    Code: "sl",
    Name: "Slovenian",
    NativeName: "Slovenščina",
    Flag: "sl",
    rtl: false,
  },
  sq: {
    Code: "sq",
    Name: "Albanian",
    NativeName: "Shqip",
    Flag: "sq",
    rtl: false,
  },
  sr: {
    Code: "sr",
    Name: "Serbian",
    NativeName: "Српски језик",
    Flag: "sr",
    rtl: false,
  },
  sv: {
    Code: "sv",
    Name: "Swedish",
    NativeName: "Svenska",
    Flag: "sv",
    rtl: false,
  },
  sw: {
    Code: "sw",
    Name: "Swahili",
    NativeName: "Kiswahili",
    Flag: "sw",
    rtl: false,
  },
  ta: {
    Code: "ta",
    Name: "Tamil",
    NativeName: "தமிழ்",
    Flag: "ta",
    rtl: false,
  },
  te: {
    Code: "te",
    Name: "Telugu",
    NativeName: "తెలుగు",
    Flag: "te",
    rtl: false,
  },
  th: { Code: "th", Name: "Thai", NativeName: "ไทย", Flag: "th", rtl: false },
  tr: {
    Code: "tr",
    Name: "Turkish",
    NativeName: "Türkçe",
    Flag: "tr",
    rtl: false,
  },
  uk: {
    Code: "uk",
    Name: "Ukrainian",
    NativeName: "Українська",
    Flag: "uk",
    rtl: false,
  },
  ur: { Code: "ur", Name: "Urdu", NativeName: "اُردُو", Flag: "ur", rtl: true },
  uz: {
    Code: "uz",
    Name: "Uzbek",
    NativeName: "Ўзбек",
    Flag: "uz",
    rtl: false,
  },
  vi: {
    Code: "vi",
    Name: "Vietnamese",
    NativeName: "Tiếng Việt",
    Flag: "vi",
    rtl: false,
  },
  zh: {
    Code: "zh",
    Name: "Chinese",
    NativeName: "中文",
    Flag: "zh",
    rtl: false,
  },
};